Throw error when can't detect flutter version.

diff --git a/.github/actions/detect-flutter-version/action.yml b/.github/actions/detect-flutter-version/action.yml
--- a/.github/actions/detect-flutter-version/action.yml
+++ b/.github/actions/detect-flutter-version/action.yml
@@ -12,4 +12,12 @@ runs:
     - name: Detect flutter version
       id: detect-flutter-version
       shell: bash
-      run: echo version=$(jq -r '.flutter' ./.fvmrc) >> $GITHUB_OUTPUT
+      run: |
+        DETECT_VERSION=$(jq -r '.flutter' ./.fvmrc)
+        echo ${DETECT_VERSION}
+        if [ "${DETECT_VERSION}" = "" ]; then
+          echo version= >> $GITHUB_OUTPUT
+        else
+          echo "Can't detect flutter version."
+          exit 1
+        fi
